### ISSUE TITLE
Required: install .NET Core runtime

### ISSUE THREAD

**Issue by ttrssreal** [TFTWPhoenix/MakeDEB#1]
.NET Core Runtime has the required library: libhostfxr

-If not installed it exits with fatal error

**Comment by TFTWPhoenix** [comment]
Yes .NET Core is required for MakeDEB because it was mainly a program to make my life easier when I wrote this. I didn't see the need to write it in C/C++. I'll add a message in the README for this. Thanks for pointing it out.

**Comment by ttrssreal** [comment]
Ok thx,
And otherwize I like it :+1:
